[package]
name = "osmium"
version = "0.1.0"
authors = ["katsurahiroyuki"]

[build-dependencies]
cc = "1.0.25"

[dependencies]
array-init = "0.0.4"
bitflags = "1.0.4"
osmium_syscall = { path = "../syscall" }
